<a href="https://colab.research.google.com/github/alokchoudharyguliya/Transformers/blob/main/Text_Summarization_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch torchvision

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torch.nn.utils.rnn import pad_sequence
from spacy.tokenizer import Tokenizer
from sklearn.model_selection import train_test_split
import spacy
import pandas as pd
import numpy as np
import os, re
from nltk.corpus import stopwords
import random
from tqdm import tqdm
import math

Tokenizer using spacy

In [3]:
nlp=spacy.load('en_core_web_sm')
tokenizer=Tokenizer(nlp.vocab)

In [4]:
# Add data from files into dataframes for easier access
def create_dataframe(source_text_path,target_text_path):
  txt_files_source=[file for file in os.listdir(source_text_path) if file.endswith('.txt')]
  txt_files_target=[file for file in os.listdir(target_text_path) if file.endswith('.txt')]
  df=pd.DataFrame(columns=['headlines','text'])
  for source,target in zip(txt_files_source,txt_files_target):
    assert source==target
    source_file_path=os.path.join(source_text_path,source)
    target_file_path=os.path.join(target_text_path,target)

    # Read the content of the file
    with open(source_file_path,'r',encoding='latin-1') as file:
      source_text=file.read()
    with open(target_file_path,'r',encoding='latin-1') as file:
      target_text=file.read()
    df.loc[len(df.index)]=[source_text,target_text]
  return df

In [5]:
def check_accuracy(output,labels):
  _, predpos=(output.max(1))
  num_samples=len(labels)
  num_correct=(predpos==labels).sum()
  return (num_correct/num_samples)*100

def save_checkpoint(state,filename='weights.pth.tar'):
  print("Saving weights")
  torch.save(state,filename)

def load_checkpoint(checkpoint,model,optim):
  print("Loading weights ---- ")
  model.load_state_dict(checkpoint['state_dict'])
  optim.load_state_dict(checkpoint['optimizer'])

Kaggle Dataset Fetch

In [6]:
import os
from google.colab import userdata

os.environ["KAGGLE_USERNAME"] = "pseudophoenix"
os.environ["KAGGLE_KEY"] = "7a2cb2f192719312c0d0e000fbb07af1"


In [7]:
!kaggle kernels pull kiranraghavendra/text-summarization-transformer-from-scratch

Source code downloaded to /content/text-summarization-transformer-from-scratch.ipynb


In [8]:
import kagglehub
# Download the specific dataset
base_path = kagglehub.dataset_download("pariza/bbc-news-summary")

100%|██████████| 8.91M/8.91M [00:00<00:00, 162MB/s]

Extracting files...


Extracting all the articles and summaries data

In [9]:
articles_root=f"{base_path}/BBC News Summary/News Articles"
summaries_root=f"{base_path}/BBC News Summary/Summaries"
df1 = create_dataframe(f"{articles_root}/business",f"{summaries_root}/business")
df2 = create_dataframe(f"{articles_root}/entertainment",f"{summaries_root}/entertainment")
df3 = create_dataframe(f"{articles_root}/politics",f"{summaries_root}/politics")
df4 = create_dataframe(f"{articles_root}/sport",f"{summaries_root}/sport")
df5 = create_dataframe(f"{articles_root}/tech",f"{summaries_root}/tech")

Combining all the df s into one dataframe

In [10]:
df=pd.concat([df1,df2,df3,df4,df5],ignore_index=True)

In [11]:
df.head()

,headlines,text
0,ID theft surge hits US consumers\n\nAlmost a q...,"The biggest slice of the 246,570 ID fraud case..."
1,Dollar gains on Greenspan speech\n\nThe dollar...,The dollar has hit its highest level against t...
2,Market unfazed by Aurora setback\n\nAs the Aur...,"Despite its string of bad luck, he pointed out..."
3,UK Coal plunges into deeper loss\n\nShares in ...,"UK Coal said it was making ""significant progre..."
4,Troubled Marsh under SEC scrutiny\n\nThe US st...,The US stock market regulator is investigating...


In [12]:
df=df.rename(columns={"headlines":"source_text","text":"summary_text"})
X,y=df['source_text'],df['summary_text']
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)
train_df=pd.DataFrame({'source_text':X_train,'summary_text':y_train})
test_df=pd.DataFrame({'source_text':X_test,'summary_text':y_test})

In [13]:
X_train.head(),X_test.head(), y_train.head(), y_test.head(), train_df.head(), test_df.head()

(1490    Hodges announces rugby retirement\n\nScarlets ...
 2001    'Blog' picked as word of the year\n\nThe term ...
 1572    European medal chances improve\n\nWhat have th...
 1840    Sun offers processing by the hour\n\nSun Micro...
 610     UK TV channel rapped for CSI ad\n\nTV channel ...
 Name: source_text, dtype: object,
 414     Metlife buys up Citigroup insurer\n\nUS bankin...
 420     Yukos accused of lying to court\n\nRussian oil...
 1644    Mourinho plots impressive course\n\nChelsea's ...
 416     Brazil approves bankruptcy reform\n\nA major r...
 1232    Abortion not a poll issue - Blair\n\nTony Blai...
 Name: source_text, dtype: object,
 1490    The 36-year-old, who has 54 caps, was Llanelli...
 2001    The term "blog" has been chosen as the top wor...
 1572    Diane Allahgreen has been our best hurdler for...
 1840    Sun likened grid computing to the development ...
 610     The promotion material was sent in brown envel...
 Name: summary_text, dtype: object,
 414     

In [14]:
contraction_mapping={}

In [15]:
def process_dataframe(df,tokenizer, text_cleaner_func):
  df['summary_text']=df['summary_text'].apply(lambda x:[token.text.lower() for token in tokenizer(text_cleaner_func(x))])
  df['source_text']=df['source_text'].apply(lambda x:[token.text.lower() for token in tokenizer(text_cleaner_func(x))])
  return df

In [16]:
# def text_cleaner(text):
#   # This is a placeholder for the actual text cleaning logic
#   # Based on common text summarization pipelines, this function would typically handle:
#   # - Removing special characters, punctuation, and numbers
#   # - Removing extra spaces
#   # - Lowercasing (though your current code does this separately)
#   # - Removing stopwords (if desired)
#   # - Expanding contractions (if using the contraction_mapping)
#   # For now, it just returns the text as is.
#   new_text = text.lower()
#   new_text = re.sub(r"[^a-zA-Z0-9 ]", "", new_text) # Remove special characters
#   new_text = re.sub(r"\s+", " ", new_text) # Remove extra spaces
#   return new_text

In [17]:
# def process_dataframe_text(df, tokenizer, text_cleaner_func):
#   df['source_text'] = df['source_text'].apply(lambda x: [token.text.lower() for token in tokenizer(text_cleaner_func(x))])
#   df['summary_text'] = df['summary_text'].apply(lambda x: [token.text.lower() for token in tokenizer(text_cleaner_func(x))])
#   return df

In [18]:
# # Tokenize and lowercase text using spacy
# train_df = process_dataframe_text(train_df, tokenizer, text_cleaner)
# test_df = process_dataframe_text(test_df, tokenizer, text_cleaner)

In [19]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
stop_words=set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [20]:
def text_cleaner(text):
  newString=text.lower()
  newString=newString.replace('"',"'")
  newString=re.sub(r'\([^)]*\)','',newString)
  newString=re.sub('"','',newString)
  # newString=' '.join([contraction_mapping[t] if t in contraction_mapping else t for t in newString.split(" ")])
  tokens=[w for w in newString.split() if not w in stop_words]
  return " ".join(tokens)

In [21]:
contraction_mapping = {"ain't": "is not", "aren't": "are not","can't": "cannot", "'cause": "because", "could've": "could have", "couldn't": "could not",

                           "didn't": "did not", "doesn't": "does not", "don't": "do not", "hadn't": "had not", "hasn't": "has not", "haven't": "have not",

                           "he'd": "he would","he'll": "he will", "he's": "he is", "how'd": "how did", "how'd'y": "how do you", "how'll": "how will", "how's": "how is",

                           "I'd": "I would", "I'd've": "I would have", "I'll": "I will", "I'll've": "I will have","I'm": "I am", "I've": "I have", "i'd": "i would",

                           "i'd've": "i would have", "i'll": "i will",  "i'll've": "i will have","i'm": "i am", "i've": "i have", "isn't": "is not", "it'd": "it would",

                           "it'd've": "it would have", "it'll": "it will", "it'll've": "it will have","it's": "it is", "let's": "let us", "ma'am": "madam",

                           "mayn't": "may not", "might've": "might have","mightn't": "might not","mightn't've": "might not have", "must've": "must have",

                           "mustn't": "must not", "mustn't've": "must not have", "needn't": "need not", "needn't've": "need not have","o'clock": "of the clock",

                           "oughtn't": "ought not", "oughtn't've": "ought not have", "shan't": "shall not", "sha'n't": "shall not", "shan't've": "shall not have",

                           "she'd": "she would", "she'd've": "she would have", "she'll": "she will", "she'll've": "she will have", "she's": "she is",

                           "should've": "should have", "shouldn't": "should not", "shouldn't've": "should not have", "so've": "so have","so's": "so as",

                           "this's": "this is","that'd": "that would", "that'd've": "that would have", "that's": "that is", "there'd": "there would",

                           "there'd've": "there would have", "there's": "there is", "here's": "here is","they'd": "they would", "they'd've": "they would have",

                           "they'll": "they will", "they'll've": "they will have", "they're": "they are", "they've": "they have", "to've": "to have",

                           "wasn't": "was not", "we'd": "we would", "we'd've": "we would have", "we'll": "we will", "we'll've": "we will have", "we're": "we are",

                           "we've": "we have", "weren't": "were not", "what'll": "what will", "what'll've": "what will have", "what're": "what are",

                           "what's": "what is", "what've": "what have", "when's": "when is", "when've": "when have", "where'd": "where did", "where's": "where is",

                           "where've": "where have", "who'll": "who will", "who'll've": "who will have", "who's": "who is", "who've": "who have",

                           "why's": "why is", "why've": "why have", "will've": "will have", "won't": "will not", "won't've": "will not have",

                           "would've": "would have", "wouldn't": "would not", "wouldn't've": "would not have", "y'all": "you all",

                           "y'all'd": "you all would","y'all'd've": "you all would have","y'all're": "you all are","y'all've": "you all have",

                           "you'd": "you would", "you'd've": "you would have", "you'll": "you will", "you'll've": "you will have",

                           "you're": "you are", "you've": "you have"}

In [22]:
def text_cleaner(text):
    if text is None:
      return ""
    if type(text) is not str:
      print(text)
      return ""
    newString = text.lower()
    newString = newString.replace('"', "'")
    newString = re.sub(r'\([^)]*\)', '', newString)
    newString = re.sub('"','', newString)
    # newString = ' '.join([contraction_mapping[t] if t in contraction_mapping else t for t in newString.split(" ")])
    newString = re.sub(r"'s\b","",newString)
    newString = re.sub("[^a-zA-Z]", " ", newString)
    tokens = [w for w in newString.split() if not w in stop_words]
    return " ".join(tokens)

In [23]:
# Tokenize and lowercase text using spacy
train_df['source_text']=train_df['source_text'].apply(lambda x:[token.text.lower() for token in tokenizer(text_cleaner(x))])
# train_df=process_dataframe(train_df,tokenizer,text_cleaner)
train_df['summary_text']=train_df['summary_text'].apply(lambda x: [token.text.lower() for token in tokenizer(text_cleaner(x))])

# Fill NaN values with empty strings before tokenization to prevent TypeError
test_df['source_text']=test_df['source_text'].fillna('').apply(lambda x:[token.text.lower() for token in tokenizer(text_cleaner(x))])
test_df['summary_text']=test_df['summary_text'].fillna('').apply(lambda x: [token.text.lower() for token in tokenizer(text_cleaner(x))])

In [24]:
train_df['source_text']=train_df['source_text'].apply(lambda x:['_START_']+x+['_END_'])
train_df['summary_text']=train_df['summary_text'].apply(lambda x:['_START_']+x+['_END_'])

test_df['source_text']=test_df['source_text'].apply(lambda x:['_START_']+x+['_END_'])
test_df['summary_text']=test_df['summary_text'].apply(lambda x:['_START_']+x+['_END_'])

In [25]:
train_df.head()

,source_text,summary_text
1490,"[_START_, hodges, announces, rugby, retirement...","[_START_, year, old, caps, llanelli, player, s..."
2001,"[_START_, blog, picked, word, year, term, blog...","[_START_, term, blog, chosen, top, word, us, d..."
1572,"[_START_, european, medal, chances, improve, e...","[_START_, diane, allahgreen, best, hurdler, ti..."
1840,"[_START_, sun, offers, processing, hour, sun, ...","[_START_, sun, likened, grid, computing, devel..."
610,"[_START_, uk, tv, channel, rapped, csi, ad, tv...","[_START_, promotion, material, sent, brown, en..."


In [28]:
# Builind vocabularies - each word has an index, note: words sorted in ascending order
all_tokens=train_df['source_text'].tolist()+train_df['summary_text'].tolist()+test_df['source_text'].tolist()+test_df['summary_text'].tolist()
source_vocab={actual_word:idx for idx, (word_num, actual_word) in enumerate(sorted(enumerate(set(token for tokens in all_tokens for token  in tokens)),key=lambda x: x[1]))}
target_vocab={actual_word: idx for idx, (word_num, actual_word) in enumerate(sorted(enumerate(set(token for tokens in all_tokens for token in tokens)), key = lambda x: x[1]))}

In [29]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("using ",device)

using  cuda


In [30]:
temp=list(sorted(source_vocab.items()))
for word, idx in temp[-5:]:
  print(word, idx)

zuluaga 27632
zurich 27633
zutons 27634
zvonareva 27635
zvyagintsev 27636


In [31]:
# Define a custom dataset class
class CustomDataset(Dataset):
  def __init__(self, source_texts, target_summaries, source_vocab, target_vocab):
    self.source_texts=source_texts
    self.target_summaries=target_summaries
    self.source_vocab=source_vocab
    self.target_vocab=target_vocab

  def __len__(self):
    return len(self.source_texts)

  def __getitem__(self,idx):
    source_text=[self.source_vocab[word] for word in self.source_texts[idx]]
    target_summary=[self.target_vocab[word] for word in self.target_summaries[idx]]
    return torch.tensor(source_text), torch.tensor(target_summary)


In [32]:
train_dataset=CustomDataset(train_df['source_text'].tolist(),train_df['summary_text'].tolist(),source_vocab, target_vocab)
test_dataset=CustomDataset(test_df['source_text'].tolist(),test_df['summary_text'].tolist(),source_vocab,target_vocab)

In [33]:
def get_max_seqlen():
  max_length=0
  for index, row in train_df.iterrows():
    # Calculate the length of the current row
    row_length=len(row['source_text'])
    # Update the maximum length if the current row length is greater
    max_length=max(max_length,row_length)
  for index, row in test_df.iterrows():
    row_length=len(row['source_text'])
    # Update the maximum length if the current row length is greater
    max_length=max(max_length,row_length)

  print("Max length in dataset ", max_length)
  return max_length

In [34]:
def collate_fn(batch):
  sources, targets=zip(*batch)
  padded_sources=pad_sequence(sources, batch_first=True)
  padded_targets=pad_sequence(targets, batch_first=True)
  return padded_sources, padded_targets

In [91]:
class MultiHeadAttention(nn.Module):
  def __init__(self, embedding_dim, num_heads):
    super(MultiHeadAttention,self).__init__()
    assert embedding_dim%num_heads==0, "embedding_dim must be divisible by num_heads"
    self.embedding_dim=embedding_dim
    self.num_heads=num_heads
    self.dim_perhead=embedding_dim//num_heads
    self.W_q=nn.Linear(embedding_dim, embedding_dim)
    self.W_k=nn.Linear(embedding_dim, embedding_dim)
    self.W_v=nn.Linear(embedding_dim, embedding_dim)
    self.W_o=nn.Linear(embedding_dim, embedding_dim)
  def scaled_dot_product_attention(self,Q,K,V, mask=None):
    # Q,K,V Shape: [Batch Size X Num_Heads X Seq_len X Dim per head]
    K=K.transpose(-2,-1)
    attn_scores=torch.matmul(Q,K)/math.sqrt(self.dim_perhead)
    if mask is not None:
      attn_scores=attn_scores.masked_fill(mask==0, -1e9)
    attn_probs=torch.softmax(attn_scores, dim=-1)
    # attn_probs Shape:
    output=torch.matmul(attn_probs, V)
    return output
  def split_heads(self, X):
    batch_size, seq_length, d_model=X.size()
    X=X.view(batch_size, seq_length, self.num_heads, self.dim_perhead)

    X=X.transpose(1,2)
    return X

  def combine_heads(self, x):
    batch_size, _ , seq_length, dim_perhead=x.size()
    x=x.transpose(1,2).contiguous()
    x=x.view(batch_size, seq_length, self.embedding_dim)
    return x

  def forward(self, Q, K, V, mask=None):
    Q=self.split_heads(self.W_q(Q))
    K=self.split_heads(self.W_k(K))
    V=self.split_heads(self.W_v(V))

    attn_output=self.scaled_dot_product_attention(Q,K,V,mask)

    output=self.W_o(self.combine_heads(attn_output))
    return output


In [92]:
class PositionWiseFeedForward(nn.Module):
  def __init__(self, d_model, d_ff):
    super(PositionWiseFeedForward,self).__init__()
    self.fc1=nn.Linear(d_model,d_ff)
    self.fc2=nn.Linear(d_ff, d_model)
  def forward(self, x):
    return self.fc2(F.relu(self.fc1(x)))

class PositionalEncoding(nn.Module):
  def __init__(self, d_model, max_seq_length):
    super(PositionalEncoding,self).__init__()
    pe=torch.zeros(max_seq_length,d_model)
    position=torch.arange(0,max_seq_length,dtype=torch.float).unsqueeze(1)
    div_term=torch.exp(torch.arange(0,d_model,2).float()*-(math.log(10000.0)/d_model))
    pe[:,0::2]=torch.sin(position*div_term)
    pe[:,1::2]=torch.cos(position*div_term)
    self.register_buffer('pe',pe.unsqueeze(0))
  def forward(self,x):
    return x+self.pe[:,:x.size(1)]

In [93]:
class EncoderLayer(nn.Module):
  def __init__(self,d_model,num_heads, d_ff, dropout):
    super(EncoderLayer,self).__init__()
    self.self_attn=MultiHeadAttention(d_model,num_heads)
    self.feed_forward=PositionWiseFeedForward(d_model,d_ff)
    self.norm1=nn.LayerNorm(d_model)
    self.norm2=nn.LayerNorm(d_model)
    self.dropout=nn.Dropout(dropout)

  def forward(self,x,mask):
    attn_output=self.self_attn(x,x,x,mask)
    x=self.norm1(x+self.dropout(attn_output))
    ff_output=self.feed_forward(x)

    x=self.norm2(x+self.dropout(ff_output))
    return x


class DecoderLayer(nn.Module):
  def __init__(self,d_model, num_heads, d_ff, dropout):
    super(DecoderLayer,self).__init__()
    self.self_attn=MultiHeadAttention(d_model,num_heads)
    self.cross_attn=MultiHeadAttention(d_model, num_heads)
    self.feed_forward=PositionWiseFeedForward(d_model,d_ff)
    self.norm1=nn.LayerNorm(d_model)
    self.norm2=nn.LayerNorm(d_model)
    self.norm3=nn.LayerNorm(d_model)
    self.dropout=nn.Dropout(dropout)

  def forward(self,x,enc_output, src_mask, tgt_mask):
    attn_output=self.self_attn(x,x,x,tgt_mask)
    x=self.norm1(x+self.dropout(attn_output))
    attn_output=self.cross_attn(x,enc_output,enc_output,src_mask)
    x=self.norm2(x+self.dropout(attn_output))
    ff_output=self.feed_forward(x)
    x=self.norm3(x+self.dropout(ff_output))
    return x

In [105]:
class Transformer(nn.Module):
  def __init__(self,src_vocab_size,tgt_vocab_size,d_model,num_heads, num_layers, d_ff, max_seq_length,drop):
    super(Transformer,self).__init__()
    self.encoder_embeddings=nn.Embedding(src_vocab_size,d_model)
    self.decoder_embedding=nn.Embedding(tgt_vocab_size,d_model)
    self.positional_encoding=PositionalEncoding(d_model,max_seq_length)
    self.encoder_layers=nn.ModuleList([EncoderLayer(d_model,num_heads, d_ff, dropout) for _ in range(num_layers)])
    self.decoder_layers=nn.ModuleList([DecoderLayer(d_model,num_heads, d_ff, dropout) for _ in range(num_layers)])
    self.fc=nn.Linear(d_model,tgt_vocab_size)
    self.dropout=nn.Dropout(dropout)

  def generate_mask(self,src,tgt):
    src_mask=(src!=0).unsqueeze(1).unsqueeze(2)
    tgt_mask=(tgt!=0).unsqueeze(1).unsqueeze(3)
    seq_length=tgt.size(1)
    nopeak_mask=(1-torch.triu(torch.ones(1,seq_length,seq_length,device=device),diagonal=1)).bool()
    tgt_mas=tgt_mask&nopeak_mask
    return src_mask, tgt_mask

  def forward(self,src,tgt):
    src_mask,tgt_mask=self.generate_mask(src,tgt)
    src_embedded=self.dropout(self.positional_encoding(self.encoder_embeddings(src)))
    tgt_embedding=self.dropout(self.positional_encoding(self.decoder_embedding(tgt)))
    enc_output=src_embedded
    for enc_layer in self.encoder_layers:
      enc_ouput=enc_layer(enc_output,src_mask)
    dec_output=tgt_embedding
    for dec_layer in self.decoder_layers:
      dec_output=dec_layer(dec_output,enc_output,src_mask,tgt_mask)
    output=self.fc(dec_output)
    return output

In [106]:
src_vocab_size=len(source_vocab)
tgt_vocab_size=len(target_vocab)
d_model=512
num_heads=8
num_layers=6
d_ff=2048
max_seq_length=get_max_seqlen()
dropout=0.1
num_workers=2
num_epochs=10
model=Transformer(src_vocab_size,tgt_vocab_size,d_model,num_heads, num_layers, d_ff, max_seq_length, dropout)
print(model)

Max length in dataset  1982
Transformer(
  (encoder_embeddings): Embedding(27637, 512)
  (decoder_embedding): Embedding(27637, 512)
  (positional_encoding): PositionalEncoding()
  (encoder_layers): ModuleList(
    (0-5): 6 x EncoderLayer(
      (self_attn): MultiHeadAttention(
        (W_q): Linear(in_features=512, out_features=512, bias=True)
        (W_k): Linear(in_features=512, out_features=512, bias=True)
        (W_v): Linear(in_features=512, out_features=512, bias=True)
        (W_o): Linear(in_features=512, out_features=512, bias=True)
      )
      (feed_forward): PositionWiseFeedForward(
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
      )
      (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (decoder_layers): ModuleList(
    (0-5): 6 x Decoder

Let's count the number of trainable parameters our Transformer has

In [107]:
trainable_params=sum(p.numel() for p in model.parameters() if p.requires_grad)
print(trainable_params)

86616565


Now we have the model, but we now need to define our loss function and the optimizer which will minimize the value of this loss function


In [108]:
criterion=nn.CrossEntropyLoss(ignore_index=0)
optimizer=optim.Adam(model.parameters(), lr=0.0001,
betas=(0.9,0.98),eps=1e-9)
scheduler=torch.optim.lr_scheduler.CosineAnnealingLR(optimizer,T_max=10,eta_min=0)

In [109]:
# Create Dataloaders
train_loader=DataLoader(train_dataset, batch_size=4,shuffle=True,collate_fn=collate_fn,num_workers=num_workers)
test_loader=DataLoader(test_dataset,batch_size=4,shuffle=False,collate_fn=collate_fn,num_workers=num_workers)

In [110]:
source_dummy,target_dummy=next(iter(train_loader))

In [111]:
print(source_dummy.shape,target_dummy.shape)

torch.Size([4, 258]) torch.Size([4, 140])


In [112]:
print(source_dummy[1])

tensor([    1, 14231,  6436, 11404, 19084,  6159, 18056, 26628, 19084,  6161,
          460, 10610, 19265,  1937,   504, 19195,  9184, 19123, 14231,  6436,
        21530, 26478,  3466, 21535, 17171,  7790, 11719,   757, 23773,  6159,
        27327, 11415, 12648, 19782, 25841, 14231,  6436, 25335, 23203, 26071,
        18611,   558, 12918, 26717, 21859, 19216, 11188,  4141, 14486, 15094,
        18056, 13657, 24344, 17935, 19265,  7693,  5008,  6641, 13916, 16927,
        18056,  5522,   442,  2854, 14348, 16205,  3466, 25025,  2102, 16644,
         1937,   504, 19195,  6159, 15024,  3787,  2437, 19084,   539, 16205,
         3466, 21344, 10512,  5216,  5674,  2448, 27338, 24432,  8727, 19088,
        14484, 22158, 15785,  2514,  4889, 27051, 12918,  6159, 14203, 21344,
        16221, 17935, 19265,  5885,  1666,  8728,  8623, 14608,  8543, 16205,
         3466,   290, 17083,  8801, 25219, 12768, 15093, 14231,  6391, 14025,
         4092, 13467, 15401, 15668, 25154, 25639,   558, 18164, 

In [113]:
print(torch.min(target_dummy),torch.max(target_dummy))

tensor(0) tensor(27479)


In [114]:
model.to(device)
source_dummy=source_dummy.to(device)
target_dummy=target_dummy.to(device)
print()

In [115]:
y_pred=model(source_dummy, target_dummy)
print(y_pred.shape,target_dummy.shape)

torch.Size([4, 140, 27637]) torch.Size([4, 140])


In [116]:
y_pred=y_pred.reshape(-1,len(target_vocab))
target_dummy=target_dummy.reshape(-1)
print(y_pred.shape,target_dummy.shape)

torch.Size([560, 27637]) torch.Size([560])


In [119]:
def train_loop(model,dataloader,loss_fun,optimizer,device):
  model.train()
  model.to(device)
  min_loss=None
  for epoch in range(num_epochs):
    losses=[]
    accuracies=[]
    loop=tqdm(enumerate(dataloader),total=len(dataloader),leave=True)
    for batch,(x,y) in loop:
      x=x.to(device)
      y=y.to(device)
      y_pred=model(x,y)
      loss=loss_fun(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
      losses.append(loss.detach().item())
      accuracy=check_accuracy(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
      accuracies.append(accuracy.detach().item())
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      scheduler.step()
      loop.set_description(f"Epoch [{epoch}/{num_epochs}]")
      loop.set_postfx(loss=loss.detach().item(),accuracy=accuracy.detach().item())
  moving_loss=sum(losses)/len(losses)
  moving_accuracy=sum(accuracies)/len(accuracies)
  checkpoint={'state_dict':model.state_dict(),'optimizer':optimizer.state_dict()}
  if min_loss==None:
    min_loss=moving_loss
    save_checkpoint(checkpoint)
  elif moving_loss<min_loss:
    min_loss=moving_loss
    save_checkpoint(checkpoint)
  print(f"Epoch {0} Loss{1}, Training Accuracy={2}".format(epoch,moving_loss, moving_accuracy))

In [121]:
def train_loop(model,dataloader,loss_fun,optimizer,device):
    model.train()
    model.to(device)
    min_loss = None
    for epoch in range(num_epochs):
        losses = []
        accuracies = []
        loop = tqdm(enumerate(dataloader), total=len(dataloader), leave=True)
        for batch,(x,y) in loop:
            # put on cuda
            x = x.to(device)
            y = y.to(device)

            # forward pass
            y_pred = model(x,y)

            # calculate loss & accuracy
            loss = loss_fun(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
            losses.append(loss.detach().item())

            accuracy = check_accuracy(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
            accuracies.append(accuracy.detach().item())

            # zero out prior gradients
            optimizer.zero_grad()

            # backprop
            loss.backward()

            # update weights
            optimizer.step()
            scheduler.step()

            # Update TQDM progress bar
            loop.set_description(f"Epoch [{epoch}/{num_epochs}] ")
            loop.set_postfix(loss=loss.detach().item(), accuracy=accuracy.detach().item())

        moving_loss = sum(losses) / len(losses)
        moving_accuracy = sum(accuracies) / len(accuracies)
        checkpoint = {'state_dict': model.state_dict(), 'optimizer': optimizer.state_dict()}
        # Save check point
        if min_loss == None:
            min_loss = moving_loss
            save_checkpoint(checkpoint)
        elif moving_loss < min_loss:
            min_loss = moving_loss
            save_checkpoint(checkpoint)
        print('Epoch {0} : Loss = {1} , Training Accuracy={2}'.format(epoch, moving_loss, moving_accuracy))

In [122]:
train_loop(model,train_loader,criterion,optimizer,device)

Epoch [0/10] : 100%|██████████| 445/445 [00:54<00:00,  8.18it/s, accuracy=47.2, loss=4.36]


Saving weights
Epoch 0 : Loss = 6.800713614131627 , Training Accuracy=23.92488934977001


Epoch [1/10] : 100%|██████████| 445/445 [00:53<00:00,  8.34it/s, accuracy=53.7, loss=3.11]


Saving weights
Epoch 1 : Loss = 3.758389205611154 , Training Accuracy=46.42243364741293


Epoch [2/10] : 100%|██████████| 445/445 [00:54<00:00,  8.10it/s, accuracy=45.5, loss=2.09]


Saving weights
Epoch 2 : Loss = 2.6266980854313027 , Training Accuracy=52.69144109661659


Epoch [3/10] : 100%|██████████| 445/445 [00:52<00:00,  8.55it/s, accuracy=77, loss=1.06]


Saving weights
Epoch 3 : Loss = 1.9957751365190142 , Training Accuracy=56.62758212143116


Epoch [4/10] : 100%|██████████| 445/445 [00:53<00:00,  8.39it/s, accuracy=79.4, loss=1.65]


Saving weights
Epoch 4 : Loss = 1.5867260103815057 , Training Accuracy=59.42858147781887


Epoch [5/10] : 100%|██████████| 445/445 [00:52<00:00,  8.46it/s, accuracy=50.2, loss=1.44]


Saving weights
Epoch 5 : Loss = 1.2906435876749875 , Training Accuracy=60.69630131239302


Epoch [6/10] : 100%|██████████| 445/445 [00:52<00:00,  8.51it/s, accuracy=73.5, loss=1.22]


Saving weights
Epoch 6 : Loss = 1.0676216000251555 , Training Accuracy=62.181980223066354


Epoch [7/10] : 100%|██████████| 445/445 [00:52<00:00,  8.52it/s, accuracy=71.9, loss=0.533]


Saving weights
Epoch 7 : Loss = 0.8927374453357096 , Training Accuracy=64.07732491653957


Epoch [8/10] : 100%|██████████| 445/445 [00:52<00:00,  8.53it/s, accuracy=46.4, loss=0.99]


Saving weights
Epoch 8 : Loss = 0.7516126555673192 , Training Accuracy=64.81063347720028


Epoch [9/10] : 100%|██████████| 445/445 [00:52<00:00,  8.45it/s, accuracy=54.1, loss=0.581]


Saving weights
Epoch 9 : Loss = 0.6372168241257078 , Training Accuracy=64.89657115721971


In [133]:
def test_loop(model,dataloader,loss_fun,device):
  model.eval()
  model.to(device)
  losses=[]
  samples,correct=0,0
  loop=tqdm(enumerate(dataloader),total=len(dataloader),leave=True)
  with torch.no_grad():
    for batch,(x,y) in loop:
      x=x.to(device)
      y=y.to(device)
      y_pred=model(x,y)
      print(x,y_pred,y)
      loss=loss_fun(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
      losses.append(loss.detach().item())
      _,predpos=y_pred.reshape(-1,len(target_vocab)).max(1)
      samples+=len(y.reshape(-1))
      correct+=(predpos==y.reshape(-1)).sum().item()
      loop.set_postfix(loss=loss.item())
  print("Final Test Accuracy = ", 100*(correct/samples))

In [134]:
test_loop(model,test_loader,criterion,device)

  2%|▏         | 2/112 [00:00<00:14,  7.78it/s, loss=1.01]

tensor([[    1, 15621,  3436,  ...,     0,     0,     0],
        [    1, 27552,   198,  ...,     0,     0,     0],
        [    1, 16165, 18521,  ...,  4030, 21804,     0],
        [    1,  3007,  1187,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.9640, 21.4622, -0.9225,  ..., -2.3160,  0.2236,  0.3772],
         [-4.6590, -2.3413, -2.6235,  ..., -4.9298, -1.5565, -1.0562],
         [-8.0121, -4.0993, -3.5968,  ..., -7.8422, -4.1278, -2.4483],
         ...,
         [-3.0725, -2.1076, -1.7783,  ..., -2.4492, -1.8272, -0.5855],
         [-3.1469, -1.9724, -1.7727,  ..., -2.5929, -1.8340, -0.6003],
         [-3.2629, -1.8329, -1.7591,  ..., -2.7617, -1.8584, -0.6016]],

        [[-2.7334, 22.2736, -0.5765,  ..., -1.9299,  0.4186,  0.3950],
         [-5.4921, -1.0500, -1.5822,  ..., -4.7833, -1.8943,  0.1513],
         [-5.0544, -0.0852, -1.1057,  ..., -5.0418, -1.8213, -0.6250],
         ...,
         [-2.7977, -1.9028, -1.6926,  ..., -2.3516, -1.4934, -1.0119],
         [

  4%|▎         | 4/112 [00:00<00:10, 10.16it/s, loss=1.39]

tensor([[    1, 25639, 18901,  ...,     0,     0,     0],
        [    1, 26515, 21160,  ...,  8503, 24291,     0],
        [    1, 20925, 25639,  ...,     0,     0,     0],
        [    1, 23059, 11180,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.1456, 22.6386, -0.4244,  ..., -1.4638,  0.5678,  0.7767],
         [-5.8600, -2.0244, -3.3632,  ..., -5.3517, -2.7237, -1.1551],
         [-4.4767, -0.9582, -2.3997,  ..., -4.1587, -1.5369, -1.4842],
         ...,
         [-1.3959, -0.5672, -1.2307,  ..., -1.0951, -0.6455, -0.7025],
         [-1.2330, -0.3832, -1.1101,  ..., -0.9779, -0.4912, -0.5687],
         [-1.1883, -0.4227, -1.1159,  ..., -1.0017, -0.3970, -0.4949]],

        [[-2.4575, 22.5686, -0.6201,  ..., -1.8031,  0.4739,  0.5110],
         [-7.9651, -1.7287, -4.1031,  ..., -7.3990, -3.9055, -2.3999],
         [-3.8599, -1.4827, -2.2035,  ..., -3.9757, -1.7746, -1.2933],
         ...,
         [-5.0981, -2.8737, -2.1590,  ..., -4.5997, -2.0820, -1.9298],
         [

  5%|▌         | 6/112 [00:00<00:11,  9.22it/s, loss=0.863]

tensor([[    1, 12284, 15922,  9987, 15093,  3106,   168, 20470, 13027, 15731,
         15922, 23848, 12284, 12285, 15922,  9987, 15093,  8615, 10126,  8047,
           168, 15093,   914, 23438, 15388, 15922,  9987,  9854,   759, 20485,
         17171, 13498,  7846, 20822, 15922,  8172,  8625,  5218, 14669, 15093,
         17239, 12341, 18483,   168, 23438, 15388, 24969, 14881, 17171, 12126,
         15098, 16654, 26811, 15922, 16262, 10721, 14177, 12284, 25122, 18678,
         15922, 12284,  4850, 26919,  8397,  5548, 15922,  9987,  8615,  8653,
         10353, 16654, 27483,  5885, 12284, 22571,  2436,  9984,  6670,  9634,
         15922, 17227, 17077,  9984, 23848, 21344, 20470,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,  

  7%|▋         | 8/112 [00:00<00:09, 10.44it/s, loss=0.882]

tensor([[    1,  4845, 22030,  9862,  4864,  1368, 26417, 13941,   353,  9862,
         21247, 22311, 16010, 16177,  9483,   981, 19284,  9260, 21344, 18999,
          4866,  9862, 21247, 16010, 13876,  6129,  5522, 21859, 24828, 18056,
         23919, 14701,  6952,  3860,  1368,  4845, 14795, 19933,  4866, 11736,
          6129, 23566, 19933,  1183, 11024, 22150, 21982, 12500,  9626,  4845,
         15847, 19349,   874, 16010, 22030,  1396,  5586,  1368, 20268, 14221,
         23062, 20557,  4199,  8552, 18194, 14750, 11024,  5885, 14888, 20735,
         26161,  1616,  2438, 24035,  1368,  3290, 15213,  1617,  3290, 19123,
         10711, 13007, 11024,   525, 17929,  2690, 26417,  1368, 20268,  6952,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 13108, 10695,   525, 16177,  1508, 

 11%|█         | 12/112 [00:01<00:07, 13.11it/s, loss=1.05]

tensor([[[-2.5261, 22.0494, -0.4780,  ..., -1.6900,  0.4808,  0.6513],
         [-6.5299, -1.5449, -3.0568,  ..., -6.3269, -3.4033, -1.5573],
         [-6.4400, -4.1795, -2.2527,  ..., -6.5343, -2.9936, -1.9045],
         ...,
         [-2.7441, -1.9470, -2.1382,  ..., -2.4736, -1.7571, -0.9434],
         [-3.0684, -1.9390, -2.1322,  ..., -2.7512, -1.8593, -0.9297],
         [-3.1434, -1.7254, -2.0435,  ..., -2.7971, -1.7790, -0.8079]],

        [[-2.2486, 22.0537, -0.5036,  ..., -1.5802,  0.4943,  0.5540],
         [-4.7445, -1.7436, -2.1937,  ..., -5.0591, -2.2153, -0.2589],
         [-4.0040, -1.1793, -2.3064,  ..., -4.0108, -3.7093, -1.2832],
         ...,
         [-2.1906, -1.5689, -1.7837,  ..., -1.9699, -1.4794, -1.0545],
         [-2.4637, -1.5534, -1.7694,  ..., -2.1950, -1.5879, -1.0368],
         [-2.6225, -1.4681, -1.7272,  ..., -2.3344, -1.5802, -0.9428]],

        [[-3.7656, 21.4733, -1.1975,  ..., -3.1376, -0.2417,  0.1601],
         [-6.5635, -1.8552, -2.9255,  ..., -6

 14%|█▍        | 16/112 [00:01<00:06, 14.60it/s, loss=1.37]

tensor([[[-1.8098, 22.3368, -0.1636,  ..., -0.9795,  0.5816,  0.9668],
         [-2.7498,  0.3822, -1.5643,  ..., -2.7659, -1.7262, -0.2882],
         [-7.3492, -4.8003, -4.5971,  ..., -7.2251, -3.7325, -2.8606],
         ...,
         [-2.8539, -1.8410, -1.5547,  ..., -2.3041, -1.4712, -0.4888],
         [-2.8940, -1.6221, -1.6004,  ..., -2.3574, -1.5530, -0.3632],
         [-2.9563, -1.6369, -1.7200,  ..., -2.4482, -1.6255, -0.3708]],

        [[-2.3915, 22.6785, -0.3484,  ..., -1.6472,  0.5131,  0.6573],
         [-2.7357,  1.4759, -0.5122,  ..., -2.2474, -1.2543, -0.2004],
         [-3.8413, -4.7006, -1.3639,  ..., -3.0325, -1.6967, -1.1445],
         ...,
         [-3.8351, -3.0394, -2.2767,  ..., -3.2929, -1.3101, -0.4088],
         [-6.9385, -6.6030, -3.7693,  ..., -7.2265, -4.1911, -1.6980],
         [-2.6671, -1.6363, -2.1875,  ..., -2.4539, -1.3026, -1.0094]],

        [[-3.4006, 21.9088, -1.2098,  ..., -2.8081, -0.1218,  0.1709],
         [-7.4361, -4.6364, -3.3508,  ..., -6

 17%|█▋        | 19/112 [00:01<00:05, 16.66it/s, loss=1.82] 

tensor([[    1, 15498, 22284,   480, 21827, 21860,   943,   480, 23916,  4927,
          6264, 13316, 15498, 19512,  9180, 21446, 17204,   480, 17107,  1896,
          1619,  7458, 22330, 21404, 13223, 14600,  6285,  4028, 25076, 21860,
           952, 21026, 19692,  2134, 24197, 24809,  8145, 26028,  5949, 21500,
          2134,  9639, 21860, 26478, 23036, 25043, 10838, 17477,  7792, 21860,
         15260, 15812, 15498,  2136,   480, 25593, 24840, 15449, 10456,  9973,
         18439,  8550, 18090, 21344,   783, 25147,  4750, 18475,   943, 26713,
         18475,  9973, 14888, 21239, 14317,  7201,  5569,   480, 15202, 18791,
         17234, 25593, 10945,  1776, 21344, 15498,  8501, 22055, 18483, 25154,
         27095, 24344,  4038, 14606, 10823,  3628, 21344,   839, 18481, 16221,
          2387, 24944, 17238, 14578,   480,   290,  5342,  2436, 18588,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,  

 20%|█▉        | 22/112 [00:01<00:05, 17.84it/s, loss=0.536]

tensor([[    1,  5546,  8047,  6102,   943,   480, 12798,  1617, 17204, 19452,
          7317, 19374, 13691,  4429, 11449, 12461,  4761,  9003, 11449,  5627,
          5522,  5271, 21344, 27479, 17131, 21344, 19084, 11449, 12461,  9523,
         15857, 27112, 13934, 27479,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,  

 23%|██▎       | 26/112 [00:01<00:05, 16.69it/s, loss=0.871]

tensor([[[-2.5870, 22.3727, -0.5677,  ..., -1.7887,  0.4063,  0.7301],
         [-6.1610,  0.2175, -2.6837,  ..., -6.1501, -2.4572, -1.2887],
         [-6.0458, -2.6961, -2.6092,  ..., -6.3618, -2.1266, -1.4760],
         ...,
         [-2.3454, -0.8588, -1.6209,  ..., -2.1954, -1.2288, -0.8223],
         [-2.5068, -0.8768, -1.6524,  ..., -2.2865, -1.1121, -0.6538],
         [-2.5943, -0.9769, -1.6944,  ..., -2.3171, -1.0094, -0.5341]],

        [[-2.8031, 21.6021, -0.7217,  ..., -2.1029,  0.1634,  0.4481],
         [-6.8793, -3.1469, -2.5793,  ..., -6.0784, -3.9240, -1.4275],
         [-8.0204, -3.8340, -3.7936,  ..., -7.9825, -3.8022, -3.5703],
         ...,
         [-2.9785, -1.5496, -1.6505,  ..., -2.5479, -1.5300, -0.6564],
         [-3.2821, -1.6726, -1.7696,  ..., -2.7820, -1.4780, -0.5210],
         [-3.3505, -1.8069, -1.8045,  ..., -2.8076, -1.3933, -0.3781]],

        [[-2.7829, 22.3321, -0.7017,  ..., -2.0437,  0.3215,  0.3512],
         [-2.1378,  0.0502, -1.3598,  ..., -2

 25%|██▌       | 28/112 [00:02<00:04, 17.14it/s, loss=1.37] 

tensor([[    1, 25135, 25556,  ...,     0,     0,     0],
        [    1,  6090,  2673,  ...,     0,     0,     0],
        [    1,  8397, 14602,  ...,     0,     0,     0],
        [    1, 26752, 25488,  ...,   307, 21932,     0]], device='cuda:0') tensor([[[-2.2382e+00,  2.2076e+01, -3.9275e-01,  ..., -1.3861e+00,
           4.1155e-01,  8.3672e-01],
         [-1.6832e+00, -4.4803e-01, -1.2457e+00,  ..., -1.8019e+00,
          -1.5394e+00, -2.1976e-02],
         [-2.1524e+00, -1.2461e+00, -9.9513e-01,  ..., -1.8108e+00,
          -5.2820e-01,  5.7720e-01],
         ...,
         [-2.4933e+00, -1.2914e+00, -1.1910e+00,  ..., -1.8019e+00,
          -1.1079e+00, -3.6697e-01],
         [-2.7216e+00, -1.1406e+00, -1.2057e+00,  ..., -2.0643e+00,
          -1.2111e+00, -3.2329e-01],
         [-2.8459e+00, -1.0430e+00, -1.2289e+00,  ..., -2.2473e+00,
          -1.3156e+00, -2.8932e-01]],

        [[-2.7878e+00,  2.1998e+01, -7.4135e-01,  ..., -2.1215e+00,
           2.6308e-01,  4.4871e-01],

 29%|██▊       | 32/112 [00:02<00:07, 11.39it/s, loss=0.974]

tensor([[    1,  7962, 21833,  ...,     0,     0,     0],
        [    1, 21136,  5273,  ..., 22124, 20332,     0],
        [    1, 19521, 20017,  ...,     0,     0,     0],
        [    1,  2142, 20701,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6720, 22.1799, -0.6452,  ..., -1.9608,  0.3896,  0.7101],
         [-4.6461, -2.2954, -1.5612,  ..., -4.9797, -1.6477, -0.6753],
         [-5.7282, -1.2038, -2.5546,  ..., -6.0322, -2.6597, -0.7106],
         ...,
         [-3.1775, -1.4422, -1.6534,  ..., -2.7863, -2.4637, -1.0329],
         [-3.2541, -1.1601, -1.6457,  ..., -2.8297, -2.4606, -1.0132],
         [-3.3419, -0.9111, -1.6359,  ..., -2.9391, -2.4537, -1.0109]],

        [[-1.7980, 22.6562, -0.2605,  ..., -1.1839,  0.8750,  0.5357],
         [-2.0082,  1.1537, -0.7851,  ..., -1.8567, -0.1789, -0.6238],
         [-1.3121, -0.9144, -0.5345,  ..., -1.6401,  0.1011, -0.6342],
         ...,
         [-1.2647, -0.2091,  0.5678,  ..., -0.9957, -1.6445, -0.5100],
         [

 30%|███       | 34/112 [00:02<00:06, 11.97it/s, loss=1.04]

tensor([[    1,  3679,  9707,  ...,     0,     0,     0],
        [    1, 15513, 15105,  ...,  4431, 24938,     0],
        [    1, 14214, 19458,  ...,     0,     0,     0],
        [    1, 11286, 12301,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.7051, 22.2201, -0.7027,  ..., -2.1030,  0.3568,  0.4970],
         [-7.1245, -1.9856, -2.8593,  ..., -5.8161, -3.0257, -1.4445],
         [-6.1316, -5.4888, -3.2961,  ..., -6.6290, -3.8778, -2.2167],
         ...,
         [-3.3322, -0.4483, -2.4088,  ..., -3.6748, -2.1028,  0.3088],
         [-3.8066, -4.8594, -1.6005,  ..., -3.2387, -1.8094, -1.2827],
         [-2.3042, -1.4389, -1.7495,  ..., -2.3638, -1.1178, -1.1000]],

        [[-2.0445, 22.5662, -0.2470,  ..., -1.3599,  0.5717,  0.6041],
         [-4.8268, -1.0632, -1.9911,  ..., -4.4119, -1.3652, -0.3287],
         [-5.1281, -1.4425, -1.6262,  ..., -4.6627, -1.9762, -1.0388],
         ...,
         [-1.5028, -0.9059, -1.2250,  ..., -1.5197, -0.9405, -0.9291],
         [

 34%|███▍      | 38/112 [00:03<00:07, 10.19it/s, loss=1.25]

tensor([[    1, 25564,  9905,  ...,     0,     0,     0],
        [    1, 16644,  5442,  ...,     0,     0,     0],
        [    1, 13570, 13966,  ..., 26359, 24262,     0],
        [    1, 18125, 24348,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6817e+00,  2.2078e+01, -5.7592e-01,  ..., -2.0293e+00,
           2.2361e-01,  5.4587e-01],
         [-3.3812e+00,  1.0987e+00, -2.5531e-01,  ..., -2.8427e+00,
          -2.2421e+00, -3.4593e-01],
         [-4.8439e+00, -2.4342e+00, -8.1250e-01,  ..., -4.4665e+00,
          -1.9769e+00, -2.0108e+00],
         ...,
         [-1.7859e+00, -2.0723e-01, -7.6711e-01,  ..., -1.1445e+00,
          -1.3656e+00, -4.8085e-01],
         [-2.0746e+00, -3.7091e-01, -9.3723e-01,  ..., -1.3355e+00,
          -1.4611e+00, -5.8949e-01],
         [-2.4120e+00, -5.6872e-01, -1.1561e+00,  ..., -1.6411e+00,
          -1.6208e+00, -7.1826e-01]],

        [[-2.2013e+00,  2.1938e+01, -4.7256e-01,  ..., -1.5266e+00,
           6.0220e-01,  9.2991e-01],

 36%|███▌      | 40/112 [00:03<00:06, 11.49it/s, loss=1.06] 

tensor([[    1,  3945, 19230, 18450,  3243, 17077, 17227, 14636, 27035, 19006,
          8918,  3135, 22024, 25295, 11408, 20191,   130,  3243, 14496, 16603,
          9581, 16032, 21344, 23443, 20352, 17065, 14551,  3243,  4044,  7593,
         27032,  3135, 15093, 19098, 17207, 25639, 14496, 24575, 16603, 12414,
         12777,  4876, 20331,  9656, 23203, 21344, 25923, 13579, 17239,  5657,
          8536, 12485, 24567, 15093, 27314,  3243,  4199,  8552,  2277, 26375,
         21344,  3243,  5726, 21044, 18475, 25008, 14891, 22030,  8879, 19832,
         19230, 25173,  9666, 21344, 16177,  4759, 24564, 20196, 17065, 21344,
         16894,  9260, 16326, 17077,  4881, 19854,  8251,   130, 18267, 14373,
          3243, 16178, 18837,  8005, 18739,  3018,  3401, 17079,  5915, 27035,
          3135, 19006, 17204, 16603, 20946, 24789,  9266, 19121, 24787,  3243,
         21344, 15447, 10718,  6392, 10610,  1913,  3243, 21344, 27338,  2204,
         25367,  1192, 26440, 13967, 11395, 23127, 2

 39%|███▉      | 44/112 [00:03<00:05, 13.42it/s, loss=0.732]

tensor([[    1, 17580,  9923, 22030,  9921, 14628,  1758, 18692,  9923,  7234,
         14412, 12226, 22162,  9913, 15922, 18267, 18054, 17261, 24158,  6775,
          3548, 21400, 27495, 27502, 26426, 13285, 27479,  8342, 22357,  9923,
          4128, 22067, 12312,  8447,  4128, 13934, 27479, 14412,  7510,  8833,
         15021,  5506, 14891,  9923,   459, 16654, 27479, 21859, 16626, 22030,
         24532,  3669, 12043,  9921, 14629, 23796, 18873, 22952, 18491, 18692,
         25076,  9921,   168, 21135, 25649, 10305,  4885, 23796, 14813,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,  

 43%|████▎     | 48/112 [00:03<00:04, 15.20it/s, loss=1.04]

tensor([[    1,  3193,  4759,  ..., 16654,  7822,     0],
        [    1,  9046,  8971,  ...,     0,     0,     0],
        [    1, 26161,  7700,  ...,     0,     0,     0],
        [    1,  2549,  2673,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-1.8698e+00,  2.2761e+01, -2.1067e-01,  ..., -1.2075e+00,
           7.7221e-01,  6.7725e-01],
         [-2.2080e+00,  1.4569e+00, -1.4069e+00,  ..., -2.2771e+00,
          -1.3038e+00,  8.8002e-02],
         [-1.4146e+00, -1.1383e+00, -9.6232e-01,  ..., -1.1902e+00,
          -7.8264e-01,  5.1387e-04],
         ...,
         [-4.8919e+00, -1.3416e+00, -1.4512e+00,  ..., -4.6242e+00,
          -2.9122e+00, -3.5696e-01],
         [-3.0628e+00, -5.9981e-01, -9.8821e-01,  ..., -2.6657e+00,
          -1.2851e+00, -5.2960e-01],
         [-1.0655e+00, -4.5170e-01, -9.8450e-01,  ..., -7.7526e-01,
          -3.0286e-01, -4.6031e-01]],

        [[-3.6708e+00,  2.1827e+01, -1.1453e+00,  ..., -2.9740e+00,
          -1.3515e-01,  1.2996e-01],

 46%|████▋     | 52/112 [00:04<00:03, 16.09it/s, loss=1.46]

tensor([[    1, 15279, 20683,  ...,     0,     0,     0],
        [    1, 16203, 12919,  ...,     0,     0,     0],
        [    1,  5115,   561,  ...,     0,     0,     0],
        [    1, 24521, 11292,  ...,  8458, 14200,     0]], device='cuda:0') tensor([[[-2.2946e+00,  2.2381e+01, -4.0166e-01,  ..., -1.5992e+00,
           5.1407e-01,  6.0478e-01],
         [-5.2974e+00, -3.7492e+00, -2.0875e+00,  ..., -4.2210e+00,
          -1.3020e+00, -9.4919e-01],
         [-6.8310e+00, -4.2172e+00, -3.7036e+00,  ..., -6.9234e+00,
          -3.2258e+00, -1.8851e+00],
         ...,
         [-1.9584e+00, -1.5614e-02, -1.1034e+00,  ..., -1.5683e+00,
          -1.0415e+00, -3.6857e-01],
         [-2.2254e+00, -4.4735e-01, -1.2328e+00,  ..., -1.8635e+00,
          -1.1927e+00, -4.4453e-01],
         [-2.6367e+00, -9.9305e-01, -1.4748e+00,  ..., -2.2938e+00,
          -1.4162e+00, -5.7426e-01]],

        [[-1.6765e+00,  2.2441e+01, -1.4169e-01,  ..., -7.4426e-01,
           7.9987e-01,  1.0632e+00],

 50%|█████     | 56/112 [00:04<00:03, 16.30it/s, loss=1.15]

tensor([[    1,  5667,  9266,  ...,     0,     0,     0],
        [    1, 21160, 24838,  ...,     0,     0,     0],
        [    1, 11212, 16958,  ...,     0,     0,     0],
        [    1,  2549,   539,  ..., 18791,   290,     0]], device='cuda:0') tensor([[[-2.1535, 22.4169, -0.2630,  ..., -1.4839,  0.6983,  0.6616],
         [-2.3623, -2.4841, -1.8900,  ..., -2.8091, -1.2400, -0.4456],
         [-3.6011, -3.1970, -2.3118,  ..., -4.0152, -1.9072, -0.8258],
         ...,
         [-2.9819, -1.9384, -2.0473,  ..., -2.7389, -1.1983, -0.8377],
         [-2.9135, -1.7995, -2.0087,  ..., -2.6386, -1.2590, -0.9827],
         [-2.7586, -1.5173, -1.8210,  ..., -2.4183, -1.2179, -0.9934]],

        [[-2.5826, 22.0828, -0.6689,  ..., -1.8344,  0.3860,  0.5943],
         [-2.1708,  0.5350, -1.3638,  ..., -1.5696, -1.0359,  0.4089],
         [-4.9948, -2.3338, -2.4290,  ..., -5.2749, -2.1205, -1.6689],
         ...,
         [-2.0988, -1.6881, -1.7875,  ..., -1.7451, -0.9907, -0.5001],
         [

 54%|█████▍    | 61/112 [00:04<00:02, 18.41it/s, loss=0.814]

tensor([[    1, 15630, 26161,  ...,     0,     0,     0],
        [    1,  2663,  2134,  ...,     0,     0,     0],
        [    1, 20989, 26717,  ...,     0,     0,     0],
        [    1, 21697, 26205,  ..., 13716, 20986,     0]], device='cuda:0') tensor([[[-3.3962, 21.6563, -1.0862,  ..., -2.5784, -0.0817,  0.1623],
         [-3.7420,  0.1918, -0.8371,  ..., -2.9901, -2.4388, -0.5501],
         [-5.4138, -2.9381, -1.1463,  ..., -4.8206, -2.2823, -2.5486],
         ...,
         [-3.7293, -2.4211, -2.6434,  ..., -3.4147, -2.1800, -1.2986],
         [-4.0572, -2.5437, -2.7052,  ..., -3.7168, -2.4128, -1.3554],
         [-4.3504, -2.5600, -2.6893,  ..., -3.9580, -2.5153, -1.3178]],

        [[-2.2518, 22.1173, -0.3824,  ..., -1.3423,  0.6274,  0.6630],
         [-4.7778, -1.8771, -2.5942,  ..., -4.8553, -1.3303, -0.8310],
         [-6.3726, -3.8643, -2.5627,  ..., -5.8359, -3.4118, -1.7105],
         ...,
         [-1.9779, -1.0391, -1.5575,  ..., -1.6318, -1.1519, -0.4424],
         [

 56%|█████▋    | 63/112 [00:04<00:02, 18.48it/s, loss=1.65]

tensor([[[-3.8513, 21.5243, -1.3423,  ..., -2.9768, -0.2459,  0.1701],
         [-3.2228, -1.2068, -1.7843,  ..., -3.5933, -1.7167, -1.1094],
         [-5.1600, -5.4084, -1.9839,  ..., -4.1836, -2.3136, -1.2848],
         ...,
         [-3.9860, -2.0578, -1.9959,  ..., -3.3172, -1.8593, -0.8902],
         [-4.1179, -2.0120, -2.0135,  ..., -3.5058, -1.9859, -0.8669],
         [-4.1407, -2.1260, -2.0778,  ..., -3.6121, -2.0634, -0.8340]],

        [[-2.6560, 22.2724, -0.5053,  ..., -1.9694,  0.3691,  0.2916],
         [-4.1835, -1.7841, -2.3290,  ..., -4.5399, -1.7752, -0.2522],
         [-2.6837, -0.8289, -0.7732,  ..., -3.0222, -1.7347, -0.9849],
         ...,
         [-2.8905, -1.8933, -1.5322,  ..., -2.4537, -1.2008, -0.8217],
         [-3.0347, -1.8586, -1.5536,  ..., -2.6463, -1.3234, -0.7789],
         [-3.0964, -1.9633, -1.6142,  ..., -2.7630, -1.4098, -0.7562]],

        [[-2.1673, 22.2417, -0.4528,  ..., -1.5333,  0.4025,  0.5889],
         [-7.3683, -0.6520, -3.6113,  ..., -7

 58%|█████▊    | 65/112 [00:04<00:02, 16.72it/s, loss=0.973]

tensor([[    1, 16287,  6846, 24759, 26258, 10424,  5320,  9157, 23839, 19374,
         21127,  9157,  9072, 21854,  8971,  9072, 17211,  9746,  9157, 24718,
          7100,  5569, 15999, 25367, 14795, 19816,  6466, 25593, 26258, 10424,
          9165, 22354, 18447, 12226, 24751, 27314, 18901, 13934,  8979,  9072,
          6846, 21419,  6438, 10918, 21344,  9072, 20112, 10998,  1302, 26161,
         27199,  4323, 17171, 24840, 27308, 22354, 17795,  9727,  8694,  8441,
         25372, 13939,  9157, 14886, 14290,  6102,  7566,  9072,  2207, 26876,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,  

 62%|██████▏   | 69/112 [00:05<00:03, 13.79it/s, loss=0.835]

tensor([[    1,  4108, 22030,  ...,     0,     0,     0],
        [    1, 22523, 10721,  ...,     0,     0,     0],
        [    1, 20165, 10711,  ...,     0,     0,     0],
        [    1, 16368, 19456,  ..., 11536, 22018,     0]], device='cuda:0') tensor([[[-2.5384e+00,  2.2041e+01, -4.3378e-01,  ..., -1.7654e+00,
           2.7926e-01,  6.0991e-01],
         [-6.8660e+00, -4.2696e+00, -3.1800e+00,  ..., -6.4431e+00,
          -4.0862e+00, -2.0090e+00],
         [-6.7577e+00, -2.2305e+00, -1.9171e+00,  ..., -6.0215e+00,
          -3.2672e+00, -2.1761e+00],
         ...,
         [-2.0056e+00,  5.2507e-02, -1.0184e+00,  ..., -1.7799e+00,
          -1.3179e+00, -1.7623e-01],
         [-1.8769e+00, -2.1062e-02, -9.5195e-01,  ..., -1.6000e+00,
          -1.2177e+00, -1.1914e-01],
         [-1.8103e+00, -1.2966e-01, -9.4511e-01,  ..., -1.5105e+00,
          -1.1581e+00, -7.4529e-02]],

        [[-2.3502e+00,  2.2306e+01, -4.2018e-01,  ..., -1.4555e+00,
           3.4908e-01,  7.3158e-01],

 65%|██████▌   | 73/112 [00:05<00:02, 14.85it/s, loss=0.86]

tensor([[    1,  8406, 10614,  ...,     0,     0,     0],
        [    1,   241,  6638,  ...,     0,     0,     0],
        [    1,  9997,  7234,  ...,     0,     0,     0],
        [    1,  9913,  1787,  ..., 18423, 13295,     0]], device='cuda:0') tensor([[[-1.8400, 22.3144, -0.1312,  ..., -0.9331,  0.6701,  0.8688],
         [-5.1203, -1.2461, -2.5836,  ..., -4.1052, -2.0437, -1.0276],
         [-5.8367, -3.5506, -2.5241,  ..., -5.5895, -3.0164, -1.1846],
         ...,
         [-3.1169, -1.6231, -1.2754,  ..., -2.3215, -1.5024, -0.2041],
         [-3.2510, -1.9811, -1.4146,  ..., -2.4441, -1.6072, -0.1681],
         [-3.6976, -2.3979, -1.6938,  ..., -2.9282, -1.8506, -0.2668]],

        [[-2.8262, 21.9766, -0.6658,  ..., -2.1612,  0.2017,  0.6325],
         [-3.7655,  2.1109, -1.7485,  ..., -3.6562, -1.3315,  0.0750],
         [-5.6399, -4.8150, -2.4551,  ..., -6.0846, -2.6360, -1.1469],
         ...,
         [-2.8298, -1.6954, -1.6153,  ..., -2.4321, -1.4159, -0.3100],
         [

 69%|██████▉   | 77/112 [00:05<00:02, 15.77it/s, loss=1.41]

tensor([[    1,  3474,  6751,  6129, 18296, 22693,   546, 14795, 23013,   469,
          3474, 22030,  6668, 25639,  9260, 18296, 25905,   977,  7566,  9494,
         10232, 25905, 11286, 18230,  9260,  6667, 22799,  5232, 11611,  8716,
         18296, 22153, 13299, 16644,   914, 21533, 21365, 27479, 18739, 18451,
         14267, 18296, 26172, 24828, 27483, 21433,  3397, 13356,  6562, 23471,
         11814, 23789, 20472, 22354, 18451,  5868,  1135, 12560, 20067,  3529,
         12598, 14317, 15024,  8589, 19123, 18296, 19933, 12443,  8995, 25905,
         18767, 25122, 26919,  9905, 21175, 19118, 21365,  6129, 19119, 11611,
          3474, 18296, 16940, 23007,   468,   759, 20925,  7790, 15731, 18456,
         18768, 11808, 15734, 21344, 18296,  4199,  8552, 20823,  7147,  9260,
         12444, 11623, 15093, 22693,  7469, 11611, 18223, 20525,  4671,  3545,
          8047,   914, 21344, 25905,  5522, 13963, 16626, 19123,  6129, 10422,
         14551, 26818, 20627, 15093,  8816, 18296, 1

 72%|███████▏  | 81/112 [00:05<00:01, 16.14it/s, loss=0.987]

tensor([[    1, 26850, 19628,  ...,  4585, 19119,     0],
        [    1,  7672,  3522,  ...,     0,     0,     0],
        [    1, 24738,  6596,  ...,     0,     0,     0],
        [    1,  6121, 16507,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-1.5124e+00,  2.2732e+01, -1.7839e-01,  ..., -1.0766e+00,
           9.5190e-01,  5.2385e-01],
         [-9.8147e-02,  4.1335e-01, -6.6166e-02,  ...,  6.3267e-02,
          -4.3529e-01,  1.4142e+00],
         [-4.4318e+00, -3.2082e+00, -2.3388e+00,  ..., -3.9645e+00,
          -2.2028e+00, -6.3558e-02],
         ...,
         [-1.4241e+00,  5.9755e-01, -1.6033e+00,  ..., -2.0503e+00,
          -1.9283e+00, -7.6184e-01],
         [-3.8016e+00, -4.5310e+00, -3.1252e+00,  ..., -3.9730e+00,
          -2.8545e+00, -2.1987e+00],
         [-1.1396e+00, -1.0914e+00, -1.6364e+00,  ..., -1.3289e+00,
          -5.7084e-01, -8.8266e-01]],

        [[-3.1149e+00,  2.1913e+01, -7.9583e-01,  ..., -2.4872e+00,
          -5.7992e-02,  2.4330e-01],

 74%|███████▍  | 83/112 [00:06<00:01, 16.70it/s, loss=1.4]  

tensor([[    1, 24479, 23411,  ...,     0,     0,     0],
        [    1,  3380,  1703,  ...,     0,     0,     0],
        [    1, 25364,  2207,  ...,     0,     0,     0],
        [    1,  9984, 14886,  ..., 11625,  4285,     0]], device='cuda:0') tensor([[[-2.7803, 21.9115, -0.7977,  ..., -2.2290,  0.2253,  0.4984],
         [-4.2711, -1.4666, -1.6664,  ..., -3.5603, -2.3028, -1.2843],
         [-3.5855, -2.2034, -1.5210,  ..., -3.8379, -1.9468, -0.0882],
         ...,
         [-2.1422, -1.1318, -1.2201,  ..., -2.0479, -1.3288, -0.6714],
         [-2.1454, -0.8351, -1.2471,  ..., -2.0340, -1.2750, -0.6210],
         [-2.3607, -0.7170, -1.4194,  ..., -2.2327, -1.2556, -0.5453]],

        [[-2.6570, 21.6155, -0.3428,  ..., -1.6569,  0.3297,  0.8892],
         [-3.2566, -0.4563, -1.0426,  ..., -2.5933, -1.6177, -1.4426],
         [-7.1000, -4.8016, -2.9354,  ..., -6.9955, -3.9601, -2.1559],
         ...,
         [-2.2459, -0.9483, -1.0394,  ..., -1.4907, -1.3063,  0.0567],
         [

 78%|███████▊  | 87/112 [00:06<00:01, 14.23it/s, loss=2.1]

tensor([[    1, 13793,  4255,  ...,     0,     0,     0],
        [    1,  4823, 11818,  ...,     0,     0,     0],
        [    1, 19619, 24317,  ...,  2387,  1493,     0],
        [    1,  6272, 24939,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.1690, 22.2327, -0.3376,  ..., -1.3720,  0.4147,  0.5955],
         [-3.1983,  0.3249, -1.7402,  ..., -3.1118, -2.0556, -0.0981],
         [-5.1511, -2.8775, -2.1663,  ..., -4.1853, -3.5835, -0.8948],
         ...,
         [-3.6720, -1.8801, -1.8711,  ..., -3.1922, -1.9758, -1.0820],
         [-3.6666, -1.7762, -1.8353,  ..., -3.1483, -1.9139, -1.0293],
         [-3.6167, -1.8153, -1.7992,  ..., -3.0080, -1.8560, -0.8999]],

        [[-2.8379, 22.0567, -0.5792,  ..., -2.1814,  0.2819,  0.4843],
         [-3.7261,  0.5209, -1.5617,  ..., -3.6876, -1.1123, -0.8692],
         [-7.4914, -4.3072, -3.5825,  ..., -7.1354, -2.4223, -2.3751],
         ...,
         [-2.5871, -1.2364, -1.4299,  ..., -2.3212, -1.3253, -0.7522],
         [

 79%|███████▉  | 89/112 [00:06<00:01, 13.33it/s, loss=1.69]

tensor([[    1, 21158, 20255,  ...,     0,     0,     0],
        [    1,  9983,  5522,  ...,     0,     0,     0],
        [    1,  9984, 27115,  ..., 21248, 13027,     0],
        [    1,  7282, 17204,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.4122, 21.8894, -0.2903,  ..., -1.8278,  0.4492,  0.4786],
         [-7.6435, -3.3690, -2.3388,  ..., -7.8888, -3.9941, -1.4813],
         [-4.5929, -4.9305, -1.4403,  ..., -3.7605, -1.9093, -0.9809],
         ...,
         [-2.3458, -0.8342, -1.3181,  ..., -2.3846, -1.3827, -0.4182],
         [-2.2669, -1.0529, -1.3430,  ..., -2.2303, -1.2871, -0.5620],
         [-2.2300, -1.3317, -1.3438,  ..., -2.1119, -1.2027, -0.6487]],

        [[-1.8626, 22.6261, -0.1369,  ..., -1.1297,  0.7121,  0.6489],
         [-3.6093, -3.0231, -1.5412,  ..., -2.5257, -1.8215, -1.1550],
         [-3.7802, -3.1917, -1.7299,  ..., -4.0215, -1.7434, -0.5960],
         ...,
         [-1.7834, -1.0738, -1.5742,  ..., -1.9227, -1.0103, -0.9710],
         [

 81%|████████▏ | 91/112 [00:06<00:01, 12.80it/s, loss=0.963]

tensor([[    1, 18481, 16221, 22008, 21955, 21044, 16654, 14874,  9157,  7267,
          2992, 18713, 25755,  5386, 12380, 14809, 20903, 25564,  9266, 14795,
          6508, 23411, 13176,  6508, 27040, 13943, 21044, 18194, 17683,  5667,
         13146,  2007,  9194, 16617,  3905, 17171, 11561, 15255, 24360, 23430,
          9157,  3690, 18485,  7278, 24545, 11656,  9157, 16713,  7894, 23703,
         24756,  4216, 14431,  6508,  3690, 14551,  1458, 24935,  3389, 22030,
          5271, 16654, 21044, 18485, 27103, 27257, 20332, 20965,  5970,  4429,
          4093,  4240,  8781,  1042, 21044,  3389,  7705, 27262, 23424,  6508,
          5652,  5842,  9157, 14886, 27262,  6508,  2169, 25947, 14874, 23411,
         10301, 18879, 24352,  6051, 11956, 21045, 12560, 24063,  2929, 17083,
         11481, 25593, 27483, 13941, 18481, 22900, 17141, 23619, 26439,  8230,
         18472, 13943, 21044,  9194, 16617,  8666, 13146,  2007, 20273, 24255,
          4216, 14551, 21247, 27299, 20273,  8253, 2

 85%|████████▍ | 95/112 [00:06<00:01, 12.72it/s, loss=0.783]

tensor([[    1, 15899, 22445,  ...,     0,     0,     0],
        [    1,  3514,   244,  ..., 14876, 21550,     0],
        [    1, 14470, 14542,  ...,     0,     0,     0],
        [    1, 12838, 23007,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-3.0072, 22.1440, -0.7430,  ..., -2.0895,  0.2457,  0.5799],
         [-4.0349, -1.7401, -1.7807,  ..., -3.6829, -1.7107, -0.7762],
         [-5.4005, -0.5126, -1.8790,  ..., -5.2694, -1.6507, -1.2498],
         ...,
         [-4.0522, -2.2023, -2.0893,  ..., -3.7453, -2.6193, -1.2574],
         [-4.0799, -2.1869, -2.1256,  ..., -3.8299, -2.6785, -1.3525],
         [-4.0839, -1.9974, -2.1625,  ..., -3.8109, -2.6397, -1.3227]],

        [[-2.6714, 22.3375, -0.5733,  ..., -1.9461,  0.6141,  0.3896],
         [-1.5166,  0.5851,  0.3878,  ..., -1.7313, -0.3389,  0.1193],
         [-3.5059,  0.2232, -1.6657,  ..., -3.3423, -0.4389,  0.1352],
         ...,
         [-4.4687, -2.6367, -1.8996,  ..., -4.7501, -2.8473, -2.1429],
         [

 87%|████████▋ | 97/112 [00:07<00:01, 12.31it/s, loss=0.749]

tensor([[    1, 25025, 21701, 17777, 26876,  4927,  1897, 22784, 19349, 18428,
         27338, 12725, 23252, 21344, 24938,  4750,  1897, 22784, 19349, 18428,
         21701, 10622, 17825, 11188, 23206,  7819, 21700, 21344, 18505, 21697,
         27338,  9482, 23888, 23638, 16626, 27522, 12838, 16205, 15314, 21344,
          5549, 11188, 19782, 13849, 14070, 22784, 23443, 17777, 16205, 15314,
         21344, 14267, 25211, 27338,  1401, 13181,  8634,  4813, 19043,  1897,
          4766,  9522, 16205, 15314,  4384,  8469, 22784,  1947, 11287, 22783,
          7803, 10298, 19548, 22780, 14177, 11188,  1260,  8879, 17467, 14377,
         19349,  7043,  4897,  1897,  4386, 14267, 25211, 13159, 27338, 14604,
         25025, 16214, 21701,  5142, 17825, 14025,  6090, 15366, 19533, 27338,
          8558,  1897,  7612, 21701,  8552,  5153, 19727, 17263,   525, 25689,
         12724,  1897, 22784, 19349, 18428, 21344,  9202, 27338, 14209,  7998,
         14264, 27338, 20371, 16796,  4909,  4457, 2

 88%|████████▊ | 99/112 [00:07<00:01, 12.00it/s, loss=1.57]

tensor([[    1,  6385, 23205,  5049, 26876, 16208, 22486, 14554,  7995, 23205,
         20251, 18724, 26876,  5050, 16208, 22486, 14554,  4845, 24133,  6385,
         21982, 16208, 22486, 25025,  2102, 16644, 26867, 19934, 26752,  8647,
         24133, 21982, 23443, 21344, 12447, 14101,   244,   573, 27383, 24655,
         14101,  8634, 26161, 23117,  6385, 15687,  4974,  9098,  5248,  2628,
         15268, 14382,  1758,   573, 12040, 18745, 16208, 22486,  1017,  2628,
          9242, 16894, 19521, 22622,  6668, 16050,  4067, 20877,   168, 16208,
         22486, 19521, 22622, 19934, 14606, 24040,   410, 10351,  2633,  4839,
         22513, 16644, 24137,  3190, 14308,  2102, 16644, 26867, 17367, 16616,
         15399, 22935, 11047,  4845, 25794, 24789, 11047, 16208, 22486, 21344,
         26161,   573,  1545, 24133, 12189, 12040,  2628, 26850,  6721, 21535,
          9242,  6129, 27338, 21859, 18357,   123, 17929,  5915, 20701, 20877,
          3429, 15731,  6385, 22153, 25916, 21344,  

 92%|█████████▏| 103/112 [00:07<00:00, 12.59it/s, loss=0.974]

tensor([[    1,  9157, 10232,  7002, 21535, 19112,  9905,  7574, 26183, 22952,
          2662, 19814,  6890, 24534, 21227, 20942,  9577,  6668, 25116, 16654,
         10130,  7573, 24534,  1768, 22952, 19934, 14874,  2821,  7002, 21344,
          9165, 27338,  1666,  2662, 19814,  9577,  7573, 18483, 23388, 26935,
         21364, 16825,   838, 13030,  8615, 25593,  4875,  7573,  9579,  2662,
         19814,  6668, 22952, 17367, 25116, 11158,  7573,  5576, 25076,  9157,
         23791, 22055, 16050,  9642,  6193, 10395,  2662, 19814, 27338, 15393,
          9577, 27338, 22147,  7573,  5248,  7002, 13943, 23790,  1016, 24534,
          1778,  9577,  2076, 15817,  2376, 26370, 26389, 26719, 25928, 23428,
         19117,  9165, 11158,  7573,  9577, 17747, 23428, 20289, 24992, 26183,
         23388,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,  

 96%|█████████▌| 107/112 [00:07<00:00, 13.93it/s, loss=0.687]

tensor([[    1, 25593, 15731, 18837, 17282,  6676, 13030, 16740,  5038, 13442,
         16924, 17171, 23232, 15093, 14025, 16740, 11736, 20289, 10951,  5167,
         21535, 20773, 26818,  9984, 18481, 16740,  9266, 13964,  9974,  5167,
          7235, 15093,  8447, 22513, 16740, 10301,  6670,  9724, 20224, 26192,
          7492, 21731,    55,  5313,   244, 22496, 25143, 21726, 14949,  5657,
         24992, 26170, 16740,  7487, 13498,  8981, 27032, 16626, 15093,  9983,
          5522, 17204, 25593, 21731, 27169,  5106,  1798,  4858,  9974,   386,
          7487,  3971, 16924, 25917, 21914, 18588, 11019,  9983, 14059,   276,
         16626, 26818, 18485,  5522, 19293,   134, 26818,  9987, 16896, 25650,
         23888,  8798,  6676, 14284, 10964,  6670, 23990, 15083,  7487,  8817,
          5661, 16740,  4429, 11678, 16626, 15770,  9984, 16626, 14203, 15922,
          9987, 12341, 22030,  8653, 16924, 11392, 19134,  6677, 17079, 19727,
          9987,  8981, 16183, 16310, 18478, 21731,  

 97%|█████████▋| 109/112 [00:08<00:00, 14.28it/s, loss=1.25] 

tensor([[    1, 11818,  6407, 13793, 15448, 19072, 11818, 24043, 22030, 19275,
         13793, 23252,  5025,  5552,   715, 21535,  8617, 24043,  6425, 11822,
          1897,   525, 13442,  6429, 22558, 22405, 20947, 25603,  5025, 26340,
         10046,  2428, 17556, 13988,  1941, 11822,  7206,  8111, 26669,  2209,
          5569,  1124,  1897,  4759,  9522,  8984,  5569,  1124,  8615, 21226,
          7615, 16654, 26882, 26986,   715,  4016, 23884, 20823,  7194, 20168,
          6846,  5552,   715, 21344,  8615, 24043, 25605, 14881, 19275, 11818,
         11648, 18420,  3560,  1401,  3106,   987,   635, 16205,  7194, 21344,
          2244, 27338, 20444, 25438, 15118, 19072, 11818,  6429, 17449, 17777,
         21982, 11539, 23447,  6429, 20350, 13793, 10426,  1708, 21344, 16834,
         18606, 21344, 17986, 15728,  3071,  6429, 22558, 22384, 16515,  1450,
          4199,  5179,  6090, 26725, 14224, 22055, 19275, 10712, 21344, 16548,
         10447, 26919,  8930, 13326, 18048, 20882,  

100%|██████████| 112/112 [00:08<00:00, 13.52it/s, loss=0.607]

tensor([[    1, 16080,  6163,  ...,     0,     0,     0],
        [    1,  3492, 22153,  ..., 22147, 19003,     0],
        [    1, 25639, 22030,  ...,     0,     0,     0],
        [    1,  1747,  2170,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6002, 22.0825, -0.6932,  ..., -1.9303,  0.2797,  0.5722],
         [-2.6506,  1.0064, -1.7045,  ..., -1.8044, -1.0872, -1.0202],
         [-0.3390,  0.0317,  1.1998,  ..., -0.1687,  0.2670,  1.0154],
         ...,
         [-2.9010, -1.3714, -1.8675,  ..., -2.5540, -1.3235, -0.4029],
         [-2.8525, -1.6103, -1.8519,  ..., -2.4844, -1.3749, -0.5123],
         [-2.7319, -1.6099, -1.7342,  ..., -2.3455, -1.3864, -0.5893]],

        [[-2.8026, 22.2369, -0.4512,  ..., -2.0741,  0.2774,  0.3487],
         [-4.6901, -2.1567, -1.1007,  ..., -4.0603, -2.4520, -0.7242],
         [ 0.6152,  1.9942,  1.1171,  ...,  0.6500,  0.4866,  1.0985],
         ...,
         [-2.5324, -1.2122, -2.0355,  ..., -2.4330, -1.1029, -1.1291],
         [

In [135]:
import torch

# Save only weights (recommended)
torch.save(model.state_dict(), "summarizer_model.pth")

In [139]:
# When using Hugging Face
# model.save_pretrained("summarizer_model")
# tokenizer.save_pretrained("summarizer_model")

In [140]:
# import shutil

# shutil.make_archive("summarizer_model", 'zip', "summarizer_model")

In [137]:
torch.save({
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
}, "checkpoint.pth")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')